os: Visual Studio 2017
version: 2.0.{build}
# environment:
#    COVERALLS_REPO_TOKEN:  
#       secure: 8JYxwCWszeAaWBr41pD17LB925K7Sk7utvKsIb1qz44i2anf9uLmvh2q0ilMQTBO
pull_requests:
  do_not_increment_build_number: false
branches:
  only:
  - master
#configuration: Release
#platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

build_script:
  - Msbuild.exe src/redmine-net20-api/redmine-net20-api.csproj /verbosity:minimal /p:BuildNetFX20=true 
  - Msbuild.exe src/redmine-net40-api/redmine-net40-api.csproj /verbosity:minimal /p:BuildNetFX40=true 
  - Msbuild.exe src/redmine-net40-api-signed/redmine-net40-api-signed.csproj /verbosity:minimal /p:BuildNetFX40=true
  - Msbuild.exe src/redmine-net45-api/redmine-net45-api.csproj /verbosity:minimal /p:BuildNetFX45=true
  - Msbuild.exe src/redmine-net45-api-signed/redmine-net45-api-signed.csproj /verbosity:minimal /p:BuildNetFX45=true
  - Msbuild.exe src/redmine-net451-api/redmine-net451-api.csproj /verbosity:minimal /p:BuildNetFX451=true
  - Msbuild.exe src/redmine-net451-api-signed/redmine-net451-api-signed.csproj /verbosity:minimal /p:BuildNetFX451=true
  - Msbuild.exe src/redmine-net452-api/redmine-net452-api.csproj /verbosity:minimal /p:BuildNetFX452=true
  - Msbuild.exe src/redmine-net452-api-signed/redmine-net452-api-signed.csproj /verbosity:minimal /p:BuildNetFX452=true

before_build:
- nuget restore

build:
  project: redmine-net-api.sln
  publish_nuget: true
  verbosity: detailed

after_build:
- ps: nuget pack build/redmine-net-api.nuspec -Version $env:appveyor_build_version
- ps: nuget pack build/redmine-net-api-signed.nuspec -Version $env:appveyor_build_version

nuget:
  account_feed: true
  project_feed: true

test: off

artifacts:
- path: '*.nupkg'

# preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
cache:
   - '%USERPROFILE%\.nuget\packages -> **\project.json'  # project.json cache

deploy:
- provider: NuGet
  api_key:
    secure: aOykHyBK5mqqlzZwbLgZnkB9qwmidaTFaLbc2ZKM2sSwBEuMV0VRF5OgKuoRehY0
  artifact: /.*\.nupkg/
  skip_symbols: true
